demo_homepage:
    path:     /
    defaults: { _controller: DemoBundle:Main:index }

api_demos:
    type: rest
    resource: DemoBundle\Controller\DemoController

ajax_auth:
    path:     /auth
    defaults: { _controller: DemoBundle:Auth:auth }
    requirements:
          _method: POST

show:
    path:     /show
    defaults: { _controller: DemoBundle:Auth:show }