demo_homepage:
    path:     /
    defaults: { _controller: DemoBundle:Main:index }

ajax_auth:
    path:     /auth
    defaults: { _controller: DemoBundle:Auth:auth }
    requirements:
          _method: POST

show:
    path:     /show
    defaults: { _controller: DemoBundle:Demo:show }
    requirements:
              _method: POST