# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        oauth_token:
            pattern: ^/oauth/v2/token
            security: false
        ajax_auth:
            pattern: ^/auth
            security: false
        show:
            pattern: ^/show
            fos_oauth: true
            stateless: true
            anonymous: false
        main:
            pattern: ^/
            security: false